default:
  push_kubernetes: false
  push_images: false

kubernetes:
  version: v1.23.1

images:
  - gcr.io/distroless/base
  - gcr.io/google.com/cloudsdktool/cloud-sdk
  - mcr.microsoft.com/powershell:nanoserve
