default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.1

images:
  - gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.20.0
  - gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.20.0
  - gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.20.0
  - gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.20.0
