default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.1

images:
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.34.0
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.34.0
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.34.0
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.34.0
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.34.0
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.34.0
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.34.0
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.34.0
  - gcr.io/distroless/base@sha256:3cebc059e7e52a4f5a389aa6788ac2b582227d7953933194764ea434f4d70d64
  - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.34.0
